// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/dag3322-oss/metrics/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetric creates a new instance of MockMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetric {
	mock := &MockMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetric is an autogenerated mock type for the Metric type
type MockMetric struct {
	mock.Mock
}

type MockMetric_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetric) EXPECT() *MockMetric_Expecter {
	return &MockMetric_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMetric
func (_mock *MockMetric) Close() {
	_mock.Called()
	return
}

// MockMetric_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMetric_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMetric_Expecter) Close() *MockMetric_Close_Call {
	return &MockMetric_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMetric_Close_Call) Run(run func()) *MockMetric_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_Close_Call) Return() *MockMetric_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetric_Close_Call) RunAndReturn(run func()) *MockMetric_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockMetric
func (_mock *MockMetric) Get(name string) (*model.Metric, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Metric, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Metric); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetric_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetric_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockMetric_Expecter) Get(name interface{}) *MockMetric_Get_Call {
	return &MockMetric_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockMetric_Get_Call) Run(run func(name string)) *MockMetric_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetric_Get_Call) Return(m *model.Metric, err error) *MockMetric_Get_Call {
	_c.Call.Return(m, err)
	return _c
}

func (_c *MockMetric_Get_Call) RunAndReturn(run func(name string) (*model.Metric, error)) *MockMetric_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockMetric
func (_mock *MockMetric) GetAll() (map[string]model.Metric, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]model.Metric
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]model.Metric, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]model.Metric); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]model.Metric)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetric_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMetric_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockMetric_Expecter) GetAll() *MockMetric_GetAll_Call {
	return &MockMetric_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockMetric_GetAll_Call) Run(run func()) *MockMetric_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetric_GetAll_Call) Return(m map[string]model.Metric, err error) *MockMetric_GetAll_Call {
	_c.Call.Return(m, err)
	return _c
}

func (_c *MockMetric_GetAll_Call) RunAndReturn(run func() (map[string]model.Metric, error)) *MockMetric_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// SetList provides a mock function for the type MockMetric
func (_mock *MockMetric) SetList(m map[string]model.Metric) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SetList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]model.Metric) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetric_SetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetList'
type MockMetric_SetList_Call struct {
	*mock.Call
}

// SetList is a helper method to define mock.On call
//   - m map[string]model.Metric
func (_e *MockMetric_Expecter) SetList(m interface{}) *MockMetric_SetList_Call {
	return &MockMetric_SetList_Call{Call: _e.mock.On("SetList", m)}
}

func (_c *MockMetric_SetList_Call) Run(run func(m map[string]model.Metric)) *MockMetric_SetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]model.Metric
		if args[0] != nil {
			arg0 = args[0].(map[string]model.Metric)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetric_SetList_Call) Return(err error) *MockMetric_SetList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetric_SetList_Call) RunAndReturn(run func(m map[string]model.Metric) error) *MockMetric_SetList_Call {
	_c.Call.Return(run)
	return _c
}

// SetOne provides a mock function for the type MockMetric
func (_mock *MockMetric) SetOne(m model.Metric) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SetOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.Metric) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetric_SetOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOne'
type MockMetric_SetOne_Call struct {
	*mock.Call
}

// SetOne is a helper method to define mock.On call
//   - m model.Metric
func (_e *MockMetric_Expecter) SetOne(m interface{}) *MockMetric_SetOne_Call {
	return &MockMetric_SetOne_Call{Call: _e.mock.On("SetOne", m)}
}

func (_c *MockMetric_SetOne_Call) Run(run func(m model.Metric)) *MockMetric_SetOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Metric
		if args[0] != nil {
			arg0 = args[0].(model.Metric)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetric_SetOne_Call) Return(err error) *MockMetric_SetOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetric_SetOne_Call) RunAndReturn(run func(m model.Metric) error) *MockMetric_SetOne_Call {
	_c.Call.Return(run)
	return _c
}
